springdoc:
  version: v1.0.0
  packages-to-scan: om.gsd.techbloghub.web.domain
  swagger-ui:
    path: /api-docs
    tags-sorter: alpha
    operations-sorter: method
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
