#Default Feign Client Logging Level Setting
spring:
  config:
    activate:
      on-profile: feign-log
logging:
  level:
    com:
      gsd:
        techbloghub:
          core:
            client:
              kakao: DEBUG
              naver: DEBUG
              woowahan: DEBUG
